<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Remittance.Core\Remittance.Core.csproj" />
    <ProjectReference Include="..\Remittance.Infrastructure\Remittance.Infrastructure.csproj" />
    <ProjectReference Include="..\Remittance.Infrastructure.Postgres\Remittance.Infrastructure.Postgres.csproj" />
  </ItemGroup>

</Project>
